version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: react-hello-world/app
    ports:
      - '8000:8000'
    volumes:
      - .:/src/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    image: react-hello-world/test
    environment:
      SELENIUM_HOST: http://selenium:4444/wd/hub
      TEST_SELENIUM: 'yes'
    depends_on:
      - phantomjs
  selenium:
    container_name: selenium
    image: selenium/hub
  phantomjs:
    image: selenium/node-phantomjs
    links:
      - selenium
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker/mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"