FROM node:6.9.5

# Create app directory
RUN mkdir -p /src/app
WORKDIR /src/app

# Install app dependencies
COPY package.json /src/app/
RUN npm install

# Bundle app source
COPY . /src/app

# Build and optimize react app
RUN npm run build

EXPOSE 8000

CMD ["./node_modules/pm2/bin/pm2-docker", "start", "--auto-exit", "--env", "production", "process.yml"]
