FROM node:6.9.5

# Create app directory
RUN mkdir -p /src/app
WORKDIR /src/app

# Install app dependencies
COPY package.json /src/app/
RUN npm install

# Bundle app source
COPY . /src/app

# defined in package.json
CMD [ "npm", "run", "lint-and-test" ]
